steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c","docker pull us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/image || exit 0"]

  - name: gcr.io/cloud-builders/docker
    args: [ "build",
            '--cache-from', "us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/image",
            '-t',
            'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/image',
            '.',
      ]
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/image'
    id: Push
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - '--platform=managed'
      - "--image"
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/image'
      - '--region=${LOCATION}'
      - '--allow-unauthenticated'
    id: Deploy
    entrypoint: gcloud

substitutions:
  _IMAGE_NAME: ${_IMAGE_NAME}
  _SERVICE_NAME: ${_SERVICE_NAME}
  _REGION: ${_REGION}
images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/image'