steps:

  - name: gcr.io/cloud-builders/docker
    args: [ "build",
            '--no-cache',
            '-t',
            '${_IMAGE_NAME}:$COMMIT_SHA',
            '.',
      ]
    id: Build
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args: ["auth","configure-docker","${_IMAGE_NAME}:$COMMIT_SHA"]
    id: Auth
    
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '${_IMAGE_NAME}:$COMMIT_SHA'
    id: Push
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - '--platform=managed'
      - '${_IMAGE_NAME}:$COMMIT_SHA'
      - '--region=${LOCATION}'
      - '--allow-unauthenticated'
    id: Deploy
    entrypoint: gcloud

substitutions:
  _IMAGE_NAME: ${_IMAGE_NAME}
  _SERVICE_NAME: ${_SERVICE_NAME}
  _REGION: ${_REGION}
images:
  - '${_IMAGE_NAME}:$COMMIT_SHA'