steps:
  - name: gcr.io/cloud-builders/docker
    args: [ "build",
            '--no-cache',
            '-t',
            '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}:${COMMIT_SHA}',
            '.',
      ]
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}:${COMMIT_SHA}'
    id: Push
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - '--platform=managed'
      - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}:${COMMIT_SHA}'
      - '--region=${LOCATION}'
      - '--allow-unauthenticated'
    id: Deploy
    entrypoint: gcloud
images:
  - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}:${COMMIT_SHA}'